### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by jgstew**
I still need to test this, but I've pulled in changes others have made to add python3 compatibility. I also fixed a few things and added a few things that were missing, as well as updated the XML Schemas.

### CODE REVIEW

**Comment by jgstew** [comment]
I have not tested Python2 backwards compatibility with these changes at the moment, but the changes were made to maintain python2 compatibility.

**Comment by jgstew** [comment]
Also, it would be useful if the license of this could be something like Apache2 like AutoPkg

@rustymyers @hansen-m

**Comment by jgstew** [comment]
I've now tested this a bunch with Python3 and everything seems to be working well. Still have not tested against Python2

**Comment by rustymyers** [comment]
Hi James,
I'll go ahead and merge these, but the main dev on this project has moved to a different git server: https://git.psu.edu/sysman/python-besapi

We can leave this one in place, but will redirect new development there.
Thanks
Rusty

**Comment by jgstew** [comment]
@rustymyers I couldn't figure out how to file a pull request or contribute on https://git.psu.edu/sysman/python-besapi

Which makes it difficult to have new development from the community there.

Also, is maintaining Python2 compatibility a goal of this project moving forward? or is it acceptable to abandon it?

**Comment by rustymyers** [comment]
It's ok to drop Python2 support. AutoPkg 2.0 is Python3, so I'd prefer not maintaining both. The older version should work for others that require older Python2.

**Pull request merged**
